// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrangepuffPortal.ConfigText.Infrastructure;

#nullable disable

namespace OrangepuffPortal.ConfigText.Infrastructure.Migrations
{
    [DbContext(typeof(ConfigTextDbContext))]
    [Migration("20260725155137_InitialConfigText")]
    partial class InitialConfigText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("configtext")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrangepuffPortal.ConfigText.Domain.Entity.ConfigTextDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CultureCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sCultureCode");

                    b.Property<DateTime?>("InsertedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int?>("InsertedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iInsertedUserId");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("sModule");

                    b.Property<string>("Note")
                        .HasColumnType("nchar(255)")
                        .HasColumnName("sNote");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("sText");

                    b.Property<string>("TextCode")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("sTextCode");

                    b.Property<string>("TextType")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sTextType");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("Module", "TextCode", "CultureCode", "TextType")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfigTextDefinition_Module_Code_Culture_Type");

                    b.ToTable("ConfigTextDefinition", "configtext");
                });
#pragma warning restore 612, 618
        }
    }
}
