// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrangepuffPortal.Identity.Infrastructure;

#nullable disable

namespace OrangepuffPortal.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.ExternalLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sProvider");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("sProviderKey");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExternalLogins_Provider_ProviderKey");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExternalLogins_UserId_Provider");

                    b.ToTable("ExternalLogins", "identity");
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.SecurityRuleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sCategoryDesc");

                    b.Property<bool>("Hidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("btHidden");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iInsertedUserId");

                    b.Property<string>("TextCode")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("sTextCode");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDesc")
                        .IsUnique()
                        .HasDatabaseName("UQ_SecurityRuleCategory_CategoryDesc");

                    b.ToTable("SecurityRuleCategory", "identity");
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.SecurityRuleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("iRuleCategoryId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sSecurityRuleCode");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sSecurityRuleDesc");

                    b.Property<bool>("Hidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("btHidden");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iInsertedUserId");

                    b.Property<int>("RuleType")
                        .HasColumnType("int")
                        .HasColumnName("iRuleType");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("iSortOrder");

                    b.Property<string>("TextCode")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)")
                        .HasColumnName("sTextCode");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_SecurityRuleItems_Code");

                    b.ToTable("SecurityRuleItems", "identity");
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.SecurityUserRuleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Allowed")
                        .HasColumnType("int")
                        .HasColumnName("iAllowed");

                    b.Property<decimal?>("AllowedDecimal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("nAllowed");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iInsertedUserId");

                    b.Property<int>("RuleItemId")
                        .HasColumnType("int")
                        .HasColumnName("iRuleItemId");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUpdatedUserId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.HasKey("Id");

                    b.HasIndex("RuleItemId");

                    b.HasIndex("UserId", "RuleItemId")
                        .IsUnique()
                        .HasDatabaseName("UQ_SecurityUserRuleItems_UserId_RuleItemId");

                    b.ToTable("SecurityUserRuleItems", "identity");
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("sDisplayName");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("sEmail");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("btActive");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("btAdmin");

                    b.Property<bool>("IsTemplateUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("btTemplateUser");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("iParentId");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("sPasswordHash");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sUsername");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Username");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.UserAvatar", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sContentType");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("binAvatar");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.HasKey("UserId");

                    b.ToTable("UserAvatars", "identity");
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.ExternalLogin", b =>
                {
                    b.HasOne("OrangepuffPortal.Identity.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.SecurityRuleItem", b =>
                {
                    b.HasOne("OrangepuffPortal.Identity.Domain.Entity.SecurityRuleCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.SecurityUserRuleItem", b =>
                {
                    b.HasOne("OrangepuffPortal.Identity.Domain.Entity.SecurityRuleItem", null)
                        .WithMany()
                        .HasForeignKey("RuleItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrangepuffPortal.Identity.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.User", b =>
                {
                    b.HasOne("OrangepuffPortal.Identity.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OrangepuffPortal.Identity.Domain.Entity.UserAvatar", b =>
                {
                    b.HasOne("OrangepuffPortal.Identity.Domain.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("OrangepuffPortal.Identity.Domain.Entity.UserAvatar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
